export const GENDER_OPTIONS = ["Male", "Female", "PreferNotToSay"] as const;
export const ETHNICITY_OPTIONS = ["Malay", "Chinese", "Malay", "Asian", "Black", "White", "Hispanic", "Other"] as const;
export const EDUCATION_OPTIONS = [
  "Less than High School",
  "High School",
  "Diploma",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctoral's Degree",
  "Professional's Degree",
] as const;
export const SENIORITY_OPTIONS = ["Entry", "Associate", "Senior", "Manager", "Director", "VP", "Others"] as const;
export const EXPERIENCE_OPTIONS = [
  "Less than one year",
  "1 year",
  "2-3 years",
  "4-5 years",
  "6-7 years",
  "8-9 years",
  "More than 10 years",
] as const;
export const COMPANY_TYPE = [
  "Startup",
  "Self-Employed",
  "Small and Medium-sized Enterprises (SMEs)",
  "Multinational Corporation (MNC)",
  "Government-Linked Company (GLC)",
  "Non-Governmental Organization (NGO) / Non-Profit Organization (NPO)",
] as const;
export const EMPLOYMENT_TYPE = ["Full-Time", "Part-Time", "Contract", "Internship"] as const;
export const INDUSTRY_OPTIONS = [
  "Agriculture",
  "Automotive",
  "Banking",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy",
  "Entertainment",
  "Financial Services",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Hospitality",
  "Information Technology",
  "Insurance",
  "Legal",
  "Logistics",
  "Manufacturing",
  "Marketing",
  "Media",
  "Mining",
  "Non-Profit",
  "Pharmaceutical",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Transportation",
  "Travel & Tourism",
  "Utilities",
  "Other",
] as const;

export const LOCATION_OPTIONS = [
  "Malaysia",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "China",
  "India",
  "South Korea",
  "Singapore",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Brazil",
  "Mexico",
  "South Africa",
  "United Arab Emirates",
  "Saudi Arabia",
  "Russia",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Argentina",
  "New Zealand",
  "Egypt",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
] as const;
